package airacle.air.parser

import airacle.air.interpreter.*

internal val VALUES = ListValue.valueOf(
    TupleValue.valueOf(
        StringValue.valueOf("zero")
    ),
    TupleValue.valueOf(
        StringValue.valueOf("b"),
        StringValue.valueOf("e"),
    ),
    TupleValue.valueOf(),
    TupleValue.valueOf(
        StringValue.valueOf("c"),
        StringValue.valueOf("b"),
        StringValue.valueOf("f"),
    ),

    TupleValue.valueOf(
        StringValue.valueOf("zero"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("zero"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("one"),
        StringValue.valueOf("one"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("two"),
        TupleValue.valueOf(
            StringValue.valueOf("zero"),
        ),
        TupleValue.valueOf(
            StringValue.valueOf("one"),
            StringValue.valueOf("one"),
        ),
    ),

    TupleValue.valueOf(
        UnitValue,
        UnitValue,
    ),
    TupleValue.valueOf(
        BoolValue.FALSE,
        BoolValue.FALSE,
        BoolValue.TRUE,
    ),
    TupleValue.valueOf(
        IntValue.valueOf(111.toBigInteger()),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        DecimalValue.valueOf("1.234".toBigDecimal()),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
        StringValue.valueOf("d"),
    ),

    TupleValue.valueOf(
        StringValue.valueOf("`"),
        StringValue.valueOf("`"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("~"),
        IntValue.ONE,
    ),
    TupleValue.valueOf(
        StringValue.valueOf("@"),
        DecimalValue.valueOf("1.2".toBigDecimal())
    ),
    TupleValue.valueOf(
        StringValue.valueOf("$"),
        TupleValue.valueOf(
            StringValue.valueOf("a"),
            StringValue.valueOf("b"),
        ),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("%"),
        ListValue.valueOf(
            IntValue.ONE,
            StringValue.valueOf("a"),
        )
    ),
    TupleValue.valueOf(
        StringValue.valueOf("^"),
        MapValue.valueOf(
            IntValue.ONE to StringValue.valueOf("a"),
        )
    ),
    TupleValue.valueOf(
        StringValue.valueOf("&"),
        UnitValue
    ),
    TupleValue.valueOf(
        StringValue.valueOf("*"),
        BoolValue.FALSE,
    ),
    TupleValue.valueOf(
        StringValue.valueOf("?"),
        TupleValue.valueOf(
            StringValue.valueOf("?"),
            StringValue.valueOf("a"),
            StringValue.valueOf("b"),
        ),
        StringValue.valueOf("c")
    ),
    TupleValue.valueOf(
        StringValue.valueOf("."),
        StringValue.valueOf("a"),
        TupleValue.valueOf(
            StringValue.valueOf("."),
            StringValue.valueOf("b"),
            StringValue.valueOf("c"),
        ),
    ),

    StringValue.valueOf("a"),
    TupleValue.valueOf(
        StringValue.valueOf("b"),
        StringValue.valueOf("a"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("two"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("two"),
        StringValue.valueOf("two"),
        StringValue.valueOf("two"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("?"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("?"),
        StringValue.valueOf("?"),
        StringValue.valueOf("?"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("?"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("."),
        TupleValue.valueOf(
            StringValue.valueOf("."),
            TupleValue.valueOf(
                StringValue.valueOf("."),
                StringValue.valueOf("a"),
                StringValue.valueOf("b"),
            ),
            StringValue.valueOf("c"),
        ),
        StringValue.valueOf("d"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("."),
        TupleValue.valueOf(
            StringValue.valueOf("."),
            TupleValue.valueOf(
                StringValue.valueOf("."),
                TupleValue.valueOf(
                    StringValue.valueOf("."),
                    TupleValue.valueOf(
                        StringValue.valueOf("~"),
                        StringValue.valueOf("a")
                    ),
                    TupleValue.valueOf(
                        StringValue.valueOf("zero")
                    ),
                ),
                TupleValue.valueOf(),
            ),
            ListValue.valueOf(),
        ),
        MapValue.valueOf(),
    ),
    TupleValue.valueOf(
        TupleValue.valueOf(
            StringValue.valueOf("c"),
            StringValue.valueOf("b"),
            StringValue.valueOf("d"),
        ),
        StringValue.valueOf("a"),
        StringValue.valueOf("e"),
    ),

    TupleValue.valueOf(
        ListValue.valueOf(
            MapValue.valueOf(
                ListValue.valueOf(
                    TupleValue.valueOf(
                        MapValue.valueOf()
                    )
                ) to TupleValue.valueOf(
                    ListValue.valueOf(
                        MapValue.valueOf()
                    )
                )
            )
        )
    ),
    ListValue.valueOf(
        ListValue.valueOf(
            TupleValue.valueOf(),
            MapValue.valueOf(),
            ListValue.valueOf(),
        ),
        MapValue.valueOf(
            ListValue.valueOf() to TupleValue.valueOf(),
            TupleValue.valueOf() to MapValue.valueOf(),
            MapValue.valueOf() to ListValue.valueOf(),
        ),
        TupleValue.valueOf(
            TupleValue.valueOf(),
            ListValue.valueOf(),
            MapValue.valueOf(),
        )
    ),
    TupleValue.valueOf(
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    ListValue.valueOf(
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    MapValue.valueOf(
        StringValue.valueOf("a") to StringValue.valueOf("b"),
        StringValue.valueOf("c") to StringValue.valueOf("d"),
        StringValue.valueOf("e") to StringValue.valueOf("f"),
        StringValue.valueOf("g") to StringValue.valueOf("h"),
    )
)