package airacle.air.parser

import airacle.air.interpreter.ListValue
import airacle.air.interpreter.MapValue
import airacle.air.interpreter.StringValue
import airacle.air.interpreter.TupleValue

internal val VALUES = ListValue.valueOf(
    TupleValue.valueOf(
        StringValue.valueOf("quit")
    ),
    TupleValue.valueOf(
        StringValue.valueOf("b"),
        StringValue.valueOf("e"),
    ),
    TupleValue.valueOf(),
    TupleValue.valueOf(
        StringValue.valueOf("c"),
        StringValue.valueOf("b"),
        StringValue.valueOf("f"),
    ),

    TupleValue.valueOf(
        StringValue.valueOf("le"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("and"),
        TupleValue.valueOf(
            StringValue.valueOf("le"),
            StringValue.valueOf("a"),
            StringValue.valueOf("b"),
        ),
        TupleValue.valueOf(
            StringValue.valueOf("le"),
            StringValue.valueOf("b"),
            StringValue.valueOf("c"),
        ),
    ),

    TupleValue.valueOf(
        StringValue.valueOf("`"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("`"),
        TupleValue.valueOf(
            StringValue.valueOf("~"),
            TupleValue.valueOf(
                StringValue.valueOf("'"),
                StringValue.valueOf("a"),
            ),
        ),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("`"),
        TupleValue.valueOf(
            TupleValue.valueOf(
                StringValue.valueOf("'"),
                TupleValue.valueOf(
                    StringValue.valueOf("~"),
                    StringValue.valueOf("a"),
                ),
            ),
            StringValue.valueOf("b"),
            TupleValue.valueOf(
                StringValue.valueOf("~"),
                TupleValue.valueOf(
                    StringValue.valueOf("le"),
                    StringValue.valueOf("a"),
                    StringValue.valueOf("b"),
                ),
            ),
        ),
    ),

    StringValue.valueOf("a"),
    TupleValue.valueOf(
        StringValue.valueOf("b"),
        StringValue.valueOf("a"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("and"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("and"),
        StringValue.valueOf("and"),
        StringValue.valueOf("and"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("and"),
        TupleValue.valueOf(
            StringValue.valueOf("and"),
            TupleValue.valueOf(
                StringValue.valueOf("and"),
                StringValue.valueOf("a"),
                StringValue.valueOf("b"),
            ),
            StringValue.valueOf("c"),
        ),
        StringValue.valueOf("d"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("and"),
        TupleValue.valueOf(
            StringValue.valueOf("and"),
            TupleValue.valueOf(
                StringValue.valueOf("and"),
                TupleValue.valueOf(
                    StringValue.valueOf("and"),
                    TupleValue.valueOf(
                        StringValue.valueOf("~"),
                        StringValue.valueOf("a")
                    ),
                    TupleValue.valueOf(
                        StringValue.valueOf("le"),
                        StringValue.valueOf("a"),
                        StringValue.valueOf("b"),
                    ),
                ),
                TupleValue.valueOf(),
            ),
            ListValue.valueOf(),
        ),
        MapValue.valueOf(),
    ),
    TupleValue.valueOf(
        TupleValue.valueOf(
            StringValue.valueOf("c"),
            StringValue.valueOf("b"),
            StringValue.valueOf("d"),
        ),
        StringValue.valueOf("a"),
        StringValue.valueOf("e"),
    ),

    TupleValue.valueOf(
        ListValue.valueOf(
            MapValue.valueOf(
                ListValue.valueOf(
                    TupleValue.valueOf(
                        MapValue.valueOf()
                    )
                ) to TupleValue.valueOf(
                    ListValue.valueOf(
                        MapValue.valueOf()
                    )
                )
            )
        )
    ),
    ListValue.valueOf(
        ListValue.valueOf(
            TupleValue.valueOf(),
            MapValue.valueOf(),
            ListValue.valueOf(),
        ),
        MapValue.valueOf(
            ListValue.valueOf() to TupleValue.valueOf(),
            TupleValue.valueOf() to MapValue.valueOf(),
            MapValue.valueOf() to ListValue.valueOf(),
        ),
        TupleValue.valueOf(
            TupleValue.valueOf(),
            ListValue.valueOf(),
            MapValue.valueOf(),
        )
    ),
    TupleValue.valueOf(
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    ListValue.valueOf(
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    MapValue.valueOf(
        StringValue.valueOf("a") to StringValue.valueOf("b"),
        StringValue.valueOf("c") to StringValue.valueOf("d"),
        StringValue.valueOf("e") to StringValue.valueOf("f"),
        StringValue.valueOf("g") to StringValue.valueOf("h"),
    ),

    // full command list

    // repl
    TupleValue.valueOf(
        StringValue.valueOf("exit"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("quit"),
    ),

    // bool
    TupleValue.valueOf(
        StringValue.valueOf("not"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("and"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("or"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("xor"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),

    // comparator
    TupleValue.valueOf(
        StringValue.valueOf("le"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("lt"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("ge"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("gt"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("eq"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("ne"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),

    // number
    TupleValue.valueOf(
        StringValue.valueOf("plus"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("minus"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("abs"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sign"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("min"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("max"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),

    // int
    TupleValue.valueOf(
        StringValue.valueOf("add"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sub"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("mul"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dii"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("rem"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dir"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("pow"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("log"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("mod"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("bitNot"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("bitAnd"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("bitOr"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("bitXor"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("bitAndNot"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("testBit"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("setBit"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("clearBit"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("flipBit"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("bitCount"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("bitLength"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("lowestSetBit"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shl"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shr"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("rand"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("seed"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),

    // decimal
    TupleValue.valueOf(
        StringValue.valueOf("precision"),
        StringValue.valueOf("a"),
    ),

    // 0
    TupleValue.valueOf(
        StringValue.valueOf("rand0"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("seed0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("round0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("add0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sub0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("mul0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("div0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dii0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("rem0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dir0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("pow0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("exp0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("log0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("ln0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shl0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shr0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sin0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("cos0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("tan0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("asin0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("acos0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atan0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atan20"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sinh0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("cosh0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("tanh0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("asinh0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("acosh0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atanh0"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),

    // 32
    TupleValue.valueOf(
        StringValue.valueOf("rand32"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("seed32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("round32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("add32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sub32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("mul32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("div32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dii32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("rem32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dir32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("pow32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("exp32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("log32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("ln32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shl32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shr32"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sin32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("cos32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("tan32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("asin32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("acos32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atan32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atan232"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sinh32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("cosh32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("tanh32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("asinh32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("acosh32"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atanh32"),
        StringValue.valueOf("a"),
    ),

    // 64
    TupleValue.valueOf(
        StringValue.valueOf("rand64"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("seed64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("round64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("add64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sub64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("mul64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("div64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dii64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("rem64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dir64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("pow64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("exp64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("log64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("ln64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shl64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shr64"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sin64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("cos64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("tan64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("asin64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("acos64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atan64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atan264"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sinh64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("cosh64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("tanh64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("asinh64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("acosh64"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atanh64"),
        StringValue.valueOf("a"),
    ),

    // 128
    TupleValue.valueOf(
        StringValue.valueOf("rand128"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("seed128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("round128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("add128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sub128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("mul128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("div128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dii128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("rem128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("dir128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("pow128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("exp128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("log128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("ln128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shl128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("shr128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sin128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("cos128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("tan128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("asin128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("acos128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atan128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atan2128"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("sinh128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("cosh128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("tanh128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("asinh128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("acosh128"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("atanh128"),
        StringValue.valueOf("a"),
    ),

    // parser
    TupleValue.valueOf(
        StringValue.valueOf("toString"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("fromString"),
        StringValue.valueOf("a"),
    ),

    // type
    TupleValue.valueOf(
        StringValue.valueOf("typeOf"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("toType"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),

    // eval
    TupleValue.valueOf(
        StringValue.valueOf("value"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("'"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("quote"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("`"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("eval"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("~"),
        StringValue.valueOf("a"),
    ),

    // control
    TupleValue.valueOf(
        StringValue.valueOf("nop"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("if"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("for"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
        StringValue.valueOf("c"),
        StringValue.valueOf("d"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("while"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("function"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("return"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("call"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),

    // context
    TupleValue.valueOf(
        StringValue.valueOf("read"),
        StringValue.valueOf("a"),
    ),
    TupleValue.valueOf(
        StringValue.valueOf("write"),
        StringValue.valueOf("a"),
        StringValue.valueOf("b"),
    ),
)